import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/PretendardVariable.woff2',
    },
  ],
  variable: '--font-pretendard',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} font-pretendard`}>
        {children}
      </body>
    </html>
  );
}
