import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ClientSessionProvider } from '@/components/Providers/ClientSessionProvider';
import { Header } from '@/components/Header/Header';
const pretendard = localFont({
  src: [
    {
      path: '../public/fonts/PretendardVariable.woff2',
    },
  ],
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} font-pretendard`}>
        {/* <Header /> */}
        {/* <ClientSessionProvider>{children}</ClientSessionProvider> */}
        {children}
      </body>
    </html>
  );
}
